export enum Interval {
  Prima = 0,
  MinorSecond = 1,
  MajorSecond = 2,
  MinorThird = 3,
  MajorThird = 4,
  PerfectFourth = 5,
  AugmentedForth = 6,
  DiminishedFifth = 6,
  PerfectFifth = 7,
  MinorSixth = 8,
  MajorSixth = 9,
  DiminishedSeventh = 9,
  MinorSeventh = 10,
  MajorSeventh = 11,
  Octave = 12,
}
